name = "todo-dispatch-worker"
main = "src/index.ts"
compatibility_date = "2024-06-10"

[observability.logs]
enabled = true
invocation_logs = true

[observability.traces]
enabled = true

[[kv_namespaces]]
binding = "PLATFORM_KV"
id = "c12b8f6b000a41299583483a7a9979a2"

[[dispatch_namespaces]]
binding = "DISPATCHER"
namespace = "todo-platform"
